name: ois_orders_mobile
description: OIS Orders Mobile - gestion des commandes Online Ink Solutions.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.0
  url_launcher: ^6.2.0
  intl: ^0.19.0
  flutter_local_notifications: ^17.2.4

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
